fast_food_restaurants = {
    "McDonald's",
    "Subway",
    "Pizza Hut",
    "Burger King",
    "KFC",
    "Domino's Pizza",
    "Taco Bell",
    "7-Eleven",
    "Wendy's",
    "Dunkin' Donuts",
    "Starbucks",
    "Chipotle Mexican Grill",
    "Arby's",
    "Chick-fil-A",
    "Papa John's",
    "Sonic Drive-In",
    "Panda Express",
    "Hardee's",
    "Five Guys",
    "Jack in the Box",
    "Little Caesars",
    "Jimmy John's",
    "Carl's Jr.",
    "Dairy Queen",
    "Panera Bread",
    "In-N-Out Burger",
    "Whataburger",
    "Popeyes Louisiana Kitchen",
    "Bojangles'",
    "Culver's",
    "White Castle",
    "Raising Cane's Chicken Fingers",
    "Zaxby's",
    "Del Taco",
    "Long John Silver's",
    "El Pollo Loco",
    "Steak 'n Shake",
    "Checkers",
    "Church's Chicken",
    "Jersey Mike's Subs",
    "Boston Market",
    "Quiznos",
    "A&W Restaurants",
    "Qdoba",
    "Tim Hortons",
    "Baskin-Robbins",
    "Denny's",
    "Captain D's",
    "Firehouse Subs",
    "Blimpie",
}
